baseURL = 'https://kairn-zhou.github.io'
languageCode = 'en-us'
title = "kairn's garden"
copyright = 'Kairn Zhou' # Used in the footer copyright mention.
enableRobotsTXT = true # IMPORTANT: set to true if you want to use the theme's genAI/LLM web crawler blocking feature.

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = '☘︎'
    pageRef = '/directory'
    weight = 20
  [[menus.main]]
    name = 'posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'notes'
    pageRef = '/notes'
    weight = 40
  [[menus.main]]
    name = 'tags'
    pageRef = '/tagslist'
    weight = 50

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

# from making github deployment workflow
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # Set how dates should appear across the site.
  # For format options, visit https://gohugo.io/functions/time/format/
  # Default: :date_long
  dateFormat = ':date_long'

  # Show content graph for single notes and posts.
  # Default: true
  showgraph = true

  # Author details for the JSON-LD structured data.
  [params.author]
    name = 'Kairn Zhou'
    email = ''

  # Homepage setup
  [params.home]
    # Display recent blog posts on the homepage.
    # Default: true
    showRecentposts = false

    # Set how many recent blog posts to show.
    # Default: 3
    recentpostsLimit = 3

    # Display recent notes on the homepage.
    # Default: true
    showRecentnotes = false

    # Set how many recent notes to show.
    # Default: 5
    recentnotesLimit = 5

  # notes page setup
  [params.notes]
    # Set the number of notes to list on each page.
    # Default: 20
    pageSize = 20

    # Show a filter option for note categories above the notes list.
    # Default: true
    showCategoryFilter = true

  # Footer setup
  [params.footer]
    # Specify the Creative Commons license to apply to your content.
    # Options: `by`, `by_sa`, `by_nc`, `by_nc_sa`, `by_nd`, `by_nc_nd`, `zero`, `none`
    # Learn more at https://creativecommons.org/share-your-work/cclicenses/
    # Default: none
    creativeCommonsLicense = 'none'

    # Show Creative Commons icons for the selected license.
    # Default: true
    showCreativeCommonsIcons = false

    # Show a credit link to the Today I Learned theme in the footer.
    # Default: true
    showThemeCredit = true

  # robots.txt setup
  # IMPORTANT: remember to set `enableRobotsTXT = true` in your site's hugo.toml file.
  [params.robotstxt]
    # Block CommonCrawl from indexing your site. CommonCrawl data is often used to train AI models.
    # Learn more at https://commoncrawl.org/ccbot
    # Default: false
    blockCC = true

    # Block various crawlers associated with AI and machine learning model training.
    # Crawler list from https://github.com/ai-robots-txt/ai.robots.txt
    # Default: false
    blockAI = true